SportMeApp/Controllers/EventCreation/EventCreationController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportMeApp.Controllers.CreateEvent1
{
    public class EventCreationController : Controller
    {
        public IActionResult CreateForm()
        {
            return View();
        }
        public IActionResult CreateConfirmation()
        {
            return View();
        }
    }
}

SportMeApp/Views/EventSpecification/GymDetail.cshtml
<head>
    <link rel="stylesheet" type="text/css" href="~/css/GymDetail.css">
</head>


<div class="web-browser">
    <div class="fitness-center-container">
        <div class="fitness-center-image"> <img class="gym-pic" src="" alt="Picture for gym"></div>
        <div class="fitness-center-details">
            <div class="center-general-info">
                <div class="center-name"></div>
                <div class="sport-icon"><img class="icon" id="icon" src="" alt="Picture for sport"></div>
            </div>
            <div class="address-block">
                <div class="center-address"></div>
            </div>
            <div class="detailed-info">
                <div class="operating-hours" id="operating-hours">
                    

                    </div>
                <div class="contact-info">
                    <div class="phone-number">[phone number]</div>
                    <div class="status">
                       
                        <span class="closing-time"></span>
                        </div>
                    <div class="rating"></div>
                    <div class="distance"></div>
             </div>
                            
                        </div>
                    </div>
                </div>
    <div class="upcoming-events-container">
        <div class="createEvent">
            <div class="create-content">
       
                    <div class="create-instruction">
                        Doesn't match what you've expected?
                    </div>
                    
                    <a class="CreateBtn" asp-area="" asp-controller="EventCreation" asp-action="CreateForm">
                        <div class="CreateBtn" id="CreateBtn"> Create One!</div>
                    </a>
            </div>
        </div>
        <div class="event-details"></div>
            </div>
            </div>
          
<script src="~/js/Event/EventUtility.js" asp-append-version="true"></script>
<script src="~/js/Event/EventSpecification.js" asp-append-version="true"></script>