ASPNetCoreCalendar/ASPNetCoreCalendar/Models/ErrorViewModel.cs
namespace ASPNetCoreCalendar.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPNetCoreCalendar/ASPNetCoreCalendar/Models/Event.cs
using System.Runtime.CompilerServices;
using ASPNetCoreCalendar.Models;


namespace ASPNetCoreCalendar.Models
{
    public class Event
    {
        public Event() 
        {
            this.Start = new EventDateTime()
            {
                TimeZone = "Eastern Time - New York"

            };

            this.End = new EventDateTime()
            {
                TimeZone = "Eastern Time - New York"

            };

        }

        public string Summary {  get; set; }
        public string Description { get; set; }
        public EventDateTime Start { get; set; }
        public EventDateTime End { get; set; }

    }
    public class EventDateTime
    {
        public string DateTime { get; set; }
        public string TimeZone { get; set; }
    }
}

ASPNetCoreCalendar/ASPNetCoreCalendar/Controllers/CalendarEventController.cs
using Microsoft.AspNetCore.Mvc;
using ASPNetCoreCalendar.Models;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using RestSharp;


namespace ASPNetCoreCalendar.Controllers
{
    public class CalendarEventController : Controller
    {
        [HttpPost]
        public ActionResult CreateEvent(Event calendarEvent)
        {
            var tokenFile = "C:\\Users\\annie\\Downloads\\ASPNetCoreCalendar-20231110T170912Z-001\\ASPNetCoreCalendar\\ASPNetCoreCalendar\\Files\\tokens.json";
            var tokens = JObject.Parse(System.IO.File.ReadAllText(tokenFile));
         
            RestClient restClient = new RestClient("https://www.googleapis.com/calendar/v3/calendars/bc7495931fde2bcd23662e0c4b828c317cd7667a38bd28caec5f45b33da3a313@group.calendar.google.com/events?key=AIzaSyDL3bVkU9hIabTo2wiRqSv8rrA26f__PIk");
            RestRequest request = new RestRequest();
     

            calendarEvent.Start.DateTime = DateTime.Parse(calendarEvent.Start.DateTime).ToString("yyyy-MM-dd'T'HH:mm:ss.fffk");
            calendarEvent.End.DateTime = DateTime.Parse(calendarEvent.End.DateTime).ToString("yyyy-MM-dd'T'HH:mm:ss.fffk");

            var model = JsonConvert.SerializeObject(calendarEvent, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            });

            request.AddHeader("Authorization", "Bearer " + tokens["access_token"]);
            request.AddParameter("application/json", model, ParameterType.RequestBody);

            var response = restClient.Post(request);

            Console.WriteLine($"Response Content: {response.Content}");


            if (response.StatusCode == System.Net.HttpStatusCode.OK) 
            {
                return RedirectToAction("Index", "Home", new { status = "success" });
            }

            return View("Error");

        }
        public IActionResult Index()
        {
            return View();
        }

       
    }
}
 

ASPNetCoreCalendar/ASPNetCoreCalendar/Controllers/HomeController.cs
using ASPNetCoreCalendar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Runtime.InteropServices.JavaScript;
using System.Text.Json;


namespace ASPNetCoreCalendar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult OauthRedirect()
        {
            var client_id = "378858678415-the1gfbovl66l9jbmobcufom12a5kche.apps.googleusercontent.com";

            var redirectUrl = "https://accounts.google.com/o/oauth2/v2/auth?" +
                "scope=https://www.googleapis.com/auth/calendar+https://www.googleapis.com/auth/calendar.events" +
                "&access_type=online&" +
                "include_granted_scopes=true&" +
                "response_type=code&" +
                "state=there&" +
                "redirect_uri=https://localhost:7292/oauth/callback&" +
                "client_id=" + client_id;

            return Redirect(redirectUrl);
        }

    }
}

ASPNetCoreCalendar/ASPNetCoreCalendar/Controllers/OAuthController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using RestSharp;



namespace ASPNetCoreCalendar.Controllers
{
    public class OAuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public void Callback(string code, string error, string state)
        {
            if (string.IsNullOrWhiteSpace(error))
            {
                this.GetTokens(code);
            }
        }

        public ActionResult GetTokens(string code)
        {
            var tokensFile = "C:\\Users\\samue\\Downloads\\ASPNetCoreCalendar-20231110T023742Z-001\\ASPNetCoreCalendar\\ASPNetCoreCalendar\\Files\\tokens.json";
            var client_id = "378858678415-the1gfbovl66l9jbmobcufom12a5kche.apps.googleusercontent.com";
            var client_secret = "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";

            RestClient restClient = new RestClient("https://oauth2.googleapis.com/token");
            RestRequest request = new RestRequest();

            request.AddQueryParameter("client_id", client_id);
            request.AddQueryParameter("client_secret", client_secret);
            request.AddQueryParameter("code", code);
            request.AddQueryParameter("grant_type", "authorization_code");
            request.AddQueryParameter("redirect_uri", "https://localhost:7292/oauth/callback");

            var response = restClient.Post(request);

            if(response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                System.IO.File.WriteAllText(tokensFile, response.Content);
                return RedirectToAction("Index", "Home");
            }

            return View("Error");


        }

        public ActionResult RefreshToken()
        {
            
           var tokenFile = "C:\\Users\\annie\\Downloads\\ASPNetCoreCalendar-20231110T170912Z-001\\ASPNetCoreCalendar\\ASPNetCoreCalendar\\Files\\tokens.json";
            var tokens = JObject.Parse(System.IO.File.ReadAllText(tokenFile));
            var client_id = "378858678415-the1gfbovl66l9jbmobcufom12a5kche.apps.googleusercontent.com";
            var client_secret = "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";


            RestClient restClient = new RestClient("https://oauth2.googleapis.com/token");
            RestRequest request = new RestRequest();

            request.AddQueryParameter("client_id", client_id);
            request.AddQueryParameter("client_secret", client_secret);
            request.AddQueryParameter("grant_type", "refresh_token");
            request.AddQueryParameter("refresh_token", tokens["refresh_token"].ToString());

            var response = restClient.Post(request);

            if(response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                JObject newTokens = JObject.Parse(response.Content);
                newTokens["refresh_token"] = tokens["refresh_token"].ToString();
                System.IO.File.WriteAllText(tokenFile, newTokens.ToString());
                return RedirectToAction("Index", "Home", new {status = "success"});
            }
            return View("Error");
        }

        public ActionResult RevokeToken()
        {
            var tokenFile = "C:\\Users\\annie\\Downloads\\ASPNetCoreCalendar-20231110T170912Z-001\\ASPNetCoreCalendar\\ASPNetCoreCalendar\\Files\\tokens.json";
            var tokens = JObject.Parse(System.IO.File.ReadAllText(tokenFile));

            RestClient restClient = new RestClient("https://oauth2.googleapis.com/revoke");
            RestRequest request = new RestRequest();

            request.AddQueryParameter("token", tokens["access_token"].ToString());

            var response = restClient.Post(request);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("Index", "Home",new {status = "success"});
            }

            return View("Error");
        }
    }
}

ASPNetCoreCalendar/ASPNetCoreCalendar/Views/CalendarEvent/_CreateEvent.cshtml
<div style="margin-top: 50px">
    <form method="post" action="CalendarEvent/CreateEvent">
        <div class="row" style="margin:10px;">
            <label for="Summary" class="col-sm-3">Summary:</label>
            <input type="text" class="col-sm-1 form-control" name="Summary" value="" autocomplete="off" /> 
        </div>
        <div class="row" style="margin:10px;">
            <label for="Description" class="col-sm-3">Description:</label>
            <input type="datetime" class="col-sm-1 form-control" name="Description" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <label for="Start.DateTime" class="col-sm-3">Start Date Time:</label>
            <input type="datetime" class="col-sm-1 form-control" name="Start.DateTime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <label for="End.DateTime" class="col-sm-3">End Date Time:</label>
            <input type="datetime" class="col-sm-1 form-control" name="End.DateTime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <input type="submit"  value="Submit" class="btn btn-primary" />
        </div>
    </form>
</div>

ASPNetCoreCalendar/ASPNetCoreCalendar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<button class="btn btn-primary" style="margin-top: 20px;" onclick="location.href = '@Url.Action("OauthRedirect", "Home")'"> Sign In</button>
<button class="btn btn-primary" style="margin-top: 20px;" onclick="location.href = '@Url.Action("RefreshToken", "OAuth")'"> Refresh Token</button>
<button class="btn btn-primary" style="margin-top: 20px;" onclick="location.href = '@Url.Action("RevokeToken", "OAuth")'"> Revoke Access</button>
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23AD1457&ctz=America%2FNew_York&src=YmM3NDk1OTMxZmRlMmJjZDIzNjYyZTBjNGI4MjhjMzE3Y2Q3NjY3YTM4YmQyOGNhZWM1ZjQ1YjMzZGEzYTMxM0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%23F6BF26" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
<div style="margin-top: 50px">
    <form method="post" action="CalendarEvent/CreateEvent">
        <div class="row" style="margin:10px;">
            <label for="Summary" class="col-sm-3">Summary:</label>
            <input type="text" class="col-sm-1 form-control" name="Summary" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <label for="Description" class="col-sm-3">Description:</label>
            <input type="datetime" class="col-sm-1 form-control" name="Description" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <label for="Start.DateTime" class="col-sm-3">Start Date Time:</label>
            <input type="datetime" class="col-sm-1 form-control" name="Start.DateTime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <label for="End.DateTime" class="col-sm-3">End Date Time:</label>
            <input type="datetime" class="col-sm-1 form-control" name="End.DateTime" value="" autocomplete="off" />
        </div>
        <div class="row" style="margin:10px;">
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    </form>
</div>

ASPNetCoreCalendar/ASPNetCoreCalendar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNetCoreCalendar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNetCoreCalendar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNetCoreCalendar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPNetCoreCalendar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>